baseURL = 'https://rubainsamuel.com/'
locale = 'en-US'
title = 'Rubain Samuel'
theme = 'ananke'
buildFuture = true

[params]
  show_reading_time = true
  favicon = "/favicon.svg"
  [params.ananke]
    custom_css = ["css/custom.css"]

[menu]
  [[menu.main]]
    name = 'Writing'
    url = '/posts/'
    weight = 1
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 2
