baseURL = 'https://rubainsamuel.com/'
languageCode = 'en-us'
title = 'Rubain Samuel'
theme = 'ananke'

[params]
  description = 'Marketing strategist. Writing about marketing, business, and technology.'
  background_color_class = "bg-dark-green"
  body_classes = "avenir bg-near-white"
  custom_css = ["css/custom.css"]

[menu]
  [[menu.main]]
    name = 'Writing'
    url = '/posts/'
    weight = 1
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 2
